### ISSUE TITLE
memory error on windows

### ISSUE THREAD

**Issue by wellpeng** [henson/ProxyPool#12]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6815f9]

goroutine 21 [running]:
gopkg.in/mgo%2ev2.(*Session).Clone(0x0, 0xc042123f78)
        C:/Users/xxx/go/src/gopkg.in/mgo.v2/session.go:1603 +0x29
github.com/henson/ProxyPool/storage.(*Storage).GetDBSession(0xc042123f38, 0xc042123fac)
        C:/Users/xxx/go/src/github.com/henson/ProxyPool/storage/storage.go:30 +0x36
github.com/henson/ProxyPool/storage.(*Storage).Count(0xc042123f38, 0x0)
        C:/Users/xxx/go/src/github.com/henson/ProxyPool/storage/storage.go:58 +0x53
github.com/henson/ProxyPool/storage.CheckProxyDB()
        C:/Users/xxx/go/src/github.com/henson/ProxyPool/storage/filter.go:36 +0xd3
main.main.func2()
        E:/git/ProxyPool/main.go:27 +0x27
created by main.main
        E:/git/ProxyPool/main.go:26 +0x110

**Comment by henson** [comment]
Please check your mongo database first
