### ISSUE TITLE
太多僵尸进程

### ISSUE THREAD

**Issue by skiloop** [henson/ProxyPool#13]
跑两天新增300个僵尸进程，都是phantomjs的

**Comment by henson** [comment]
说明phantomjs没有正常被关闭
`fetcher, err := phantomjs.NewFetcher(2016, nil)
	defer fetcher.ShutDownPhantomJSServer()`

如果修改了源码，请检查下如上代码是否被正确执行；如果没有修改源码，请检查下系统和phantomjs的设置。我服务器上运行至今，不存在你说的问题，你也是第一个反映此问题的使用者。

**Comment by 961900832** [comment]
![image](https://user-images.githubusercontent.com/19699561/39558012-0a56d2c6-4ebe-11e8-8ef2-734f05df77db.png)

我也出现了这个问题，服务隔一段时间出现一次上图的信息，然后会启一个`phantomjs`进程

**Comment by henson** [comment]
可能是有些代理采集进程失效了，因为有段时间没改代码了，一些代理网站都发生了变化，采集规则变了
