### ISSUE TITLE
ip池里的代理好多都不能用

### ISSUE THREAD

**Issue by 961900832** [henson/ProxyPool#14]
![image](https://user-images.githubusercontent.com/19699561/39557803-d47408f0-4ebc-11e8-994c-298468cf43ee.png)

#### 代理不能用的现象特别频繁
从代理池中拿出代理ip后，设置好代理，基本上10个里有9个不能用。是因为代理过期了么？

**Comment by henson** [comment]
两个原因：一，免费的代理，确实质量不怎么高；二，目前是通过访问http://httpbin.org/验证代理IP有效性的，但是验证出来的结果只代表对httpbin.org有效，未必对您要访问的网站有效，您可以在代码中改成对您需访问的网站进行有效性验证。
感谢使用，如有问题，欢迎反馈！

**Comment by 961900832** [comment]
感谢回复！
确实是这样，以现在的观察情况来说，代理池中的ip确实对 `httpbin.org` 有效。
