### ISSUE TITLE
跑了2个小时自己挂了

### ISSUE THREAD

**Issue by netaxcess** [henson/ProxyPool#2]
2017/05/10 10:57:55 All getters finished.
2017/05/10 10:59:28 Chan: 144, IP: 275
2017/05/10 11:01:28 Chan: 0, IP: 277
panic: runtime error: index out of range

goroutine 8554 [running]:
panic(0x6daf40, 0xc042006060)
        C:/Go/src/runtime/panic.go:500 +0x1af
github.com/henson/ProxyPool/getter.IP66(0x0, 0x0, 0x0)
        E:/golang/src/github.com/henson/ProxyPool/getter/66ip.go:20 +0x759
main.run.func1(0xc042172060, 0xc04222a4b0, 0x768160)
        E:/golang/src/github.com/henson/ProxyPool/main.go:66 +0x32
created by main.run
        E:/golang/src/github.com/henson/ProxyPool/main.go:71 +0x16b
exit status 2

**Comment by henson** [comment]
因为限制了mgo数据库连接数，所以数据库并行处理效率变慢，队列容量激增，超出上限

> ipChan := make(chan *models.IP, 1000)

把1000这个设置调高，比如2000就可以了

**Comment by netaxcess** [comment]
达到2000的时候。也会挂吧。好像报的是henson/ProxyPool/getter/66ip.go:20 +0x759
是不是body = strings.Split(body, "c.js'></script>")[1] ，当没采集到IP的时候。这个应该溢出了吧。

**Comment by henson** [comment]
不是，是超出队列容量了

> panic: runtime error: index out of range
