### ISSUE TITLE
运行后报错

### ISSUE THREAD

**Issue by fotomxq** [henson/ProxyPool#3]
按照步骤安装完成后，编译并运行后出现了如下错误，请问是什么原因？谢谢！

panic: runtime error: slice bounds out of range

goroutine 26 [running]: github.com/henson/ProxyPool/getter.IP181(0x0, 0x0, 0x0) C:/works/golang/src/github.com/henson/ProxyPool/getter/ip181.go:40 +0x636 main.run.func1(0xc042032480, 0xc0420b8270, 0x7bc560) C:/works/golang/src/github.com/henson/ProxyPool/main.go:66 +0x32 created by main.run C:/works/golang/src/github.com/henson/ProxyPool/main.go:71 +0x15c Web server running on port 2017 Web server running on portW e2b0 1s6e rver running on port 2015

**Comment by henson** [comment]
是不是改了main.go？

**Comment by henson** [comment]
http://www.ip181.com/ 这个网站挂了，采集不到数据了，所以出错了，稍等下我更新下代码。
