### ISSUE TITLE
data/ProxyPool.db这个文件在哪呢

### ISSUE THREAD

**Issue by shanewni** [henson/proxypool#34]
; For "sqlite3" and "tidb", use absolute path when you start as service
PATH = data/ProxyPool.db

**Comment by sndnvaps** [comment]
只测试了sqlite3,但是实际的效果不好， Sqlite3会锁死数据库，无法并发对其操作。不建议使用

**Comment by shanewni** [comment]
我的理解是xorm会生成一个.db文件，这个文件记录了数据库创建的全过程。难道ProxyPool.db不是记录数据库创建全过程的文件吗？
印象中的.db文件是这样的：
`/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`lottery` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `lottery`;

/*Table structure for table `lt_blackip` */

DROP TABLE IF EXISTS `lt_blackip`;

CREATE TABLE `lt_blackip` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ip` varchar(50) NOT NULL DEFAULT '' COMMENT 'IP地址',
  `blacktime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '黑名单限制到期时间',
  `sys_created` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `sys_updated` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ip` (`ip`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

/*Data for the table `lt_blackip` */

insert  into `lt_blackip`(`id`,`ip`,`blacktime`,`sys_created`,`sys_updated`) values (1,'127.0.0.1',0,0,1532606350);

/*Table structure for table `lt_code` */

DROP TABLE IF EXISTS `lt_code`;`

**Comment by sndnvaps** [comment]
你可以创建一个data目录，ProxyPool.db会在运行时生成的。

**Comment by shanewni** [comment]
谢谢你，虽然我成功运行后没有发现data文件夹出现.db文件，但这已经不重要了，我已经运行起来了。

**Comment by sndnvaps** [comment]
Not thanks
