### ISSUE TITLE
麻烦看一下，这报错了，ubuntu编译后，第一次运行

### ISSUE THREAD

**Issue by ayaya118** [henson/proxypool#37]
root@cloud:~/gopath/src/github.com/henson/proxypool# ./proxypool 
2019/04/27 23:34:38 [TRACE] Log path: 
2019/04/27 23:34:38 [TRACE] Log Mode: File (Info)
2019/04/27 23:34:38 [ INFO] ProxyPool 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x81a450]

goroutine 1 [running]:
github.com/go-xorm/xorm.(*Session).Init(0xc0000fab00)
	/root/gopath/src/github.com/go-xorm/xorm/session.go:94 +0x200
github.com/go-xorm/xorm.(*Engine).NewSession(...)
	/root/gopath/src/github.com/go-xorm/xorm/engine.go:315
github.com/go-xorm/xorm.(*Engine).Where(0x0, 0x9fc1a0, 0xb84060, 0xc0001527f0, 0x1, 0x1, 0xc0001fff30)
	/root/gopath/src/github.com/go-xorm/xorm/engine.go:592 +0x57
github.com/henson/proxypool/pkg/models.countIps(0x8)
	/root/gopath/src/github.com/henson/proxypool/pkg/models/ip.go:39 +0x97
github.com/henson/proxypool/pkg/models.CountIPs(...)
	/root/gopath/src/github.com/henson/proxypool/pkg/models/ip.go:45
main.main()
	/root/gopath/src/github.com/henson/proxypool/main.go:45 +0xde

**Comment by henson** [comment]
没有配置相应参数，conf/app.ini，数据库、日志配置和代理获取接口配置
