### ISSUE TITLE
gomodule模式下报错

### ISSUE THREAD

**Issue by Felyne** [henson/proxypool#50]
gomodule开启后
1.go mod init
2.go mod tidy
然后报错
github.com/go-xorm/core@v0.6.3: parsing go.mod: unexpected module path "xorm.io/core"

**Comment by sndnvaps** [comment]
https://github.com/henson/proxypool/pull/49/commits/5cab27dd0efae0f33ad120f32b0834fca8d28f4b
用这个commit,就可以解决你的问题了。。

**Comment by Felyne** [comment]
好了，谢谢

**Comment by af913337456** [comment]
@sndnvaps @Felyne  怎样在 mod 文件指定 5cab27d ？

**Comment by sndnvaps** [comment]
@af913337456 抱歉了，我没有使用mod
