### ISSUE TITLE
IP重复过滤问题

### ISSUE THREAD

**Issue by CodeingMonkey** [henson/proxypool#52]
![image](https://user-images.githubusercontent.com/20737017/65303535-e5f0c780-dbb0-11e9-9c95-8e3695f7c8aa.png)
查看代码 的时候，看到这段代码的CheckIP的代码：
![image](https://user-images.githubusercontent.com/20737017/65303574-06208680-dbb1-11e9-8d62-54155cf28876.png)
这里其实是没有判断，数据表中是否有这个IP的话，无论有没有都是直接去更新数据表的记录。在配合第一张图的ProxyAdd，其实是没有判断是嘛。。如果有重复IP就不管了，就直接插入。。

**Comment by henson** [comment]
这个版本的确实没做去重

**Comment by CodeingMonkey** [comment]
嗷嗷嗷哦  好的好的
