### ISSUE TITLE
go get 时候报错 undefined: clog.CONSOLE

### ISSUE THREAD

**Issue by syumi-1** [henson/proxypool#59]
PS D:\WorkSpace\GO\proxy> go get -u github.com/henson/proxypool
github.com/henson/proxypool/pkg/setting

D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:61:11: undefined: clog.CONSOLE
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:61:43: cannot use clog.ConsoleConfig literal (type clog.ConsoleConfig) as type clog.Initer in argument to clog.New
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:65:14: cannot use 2 (type int) as type string in argument to clog.Fatal
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:89:14: cannot use 2 (type int) as type string in argument to clog.Fatal
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:98:14: cannot use 2 (type int) as type string in argument to clog.Fatal
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:105:14: cannot use 2 (type int) as type string in argument to clog.Fatal
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:137:27: undefined: clog.LEVEL
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:148:15: cannot use 2 (type int) as type string in argument to clog.Fatal
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:162:10: undefined: clog.MODE
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:163:8: undefined: clog.CONSOLE
D:\DevEnv\GOPATH\src\github.com\henson\proxypool\pkg\setting\setting.go:163:8: too many errors

**Comment by sndnvaps** [comment]
就这问题，我提交了个 pr https://github.com/henson/proxypool/pull/60 合并后，就能解决了。

**Comment by syumi-1** [comment]
@sndnvaps 
好的 知道了 谢谢

**Comment by sndnvaps** [comment]
@syumi-1 提交的补丁已经合并。
