### ISSUE TITLE
Phantomjs用Docker装了可以用么？

### ISSUE THREAD

**Issue by XiaoxiaYao** [henson/proxypool#69]
还是说必须装在本机上？

**Comment by sndnvaps** [comment]
@XiaoxiaYao 
这个还真没有试过，理论上本机和docker容器中都可以用，主要是程序能调用到就可以。。。

**Comment by XiaoxiaYao** [comment]
> @XiaoxiaYao
> 这个还真没有试过，理论上本机和docker容器中都可以用，主要是程序能调用到就可以。。。

可以的。我试了， 有Docker image。
