### ISSUE TITLE
咱们这个检测代理是否可以用的功能有点问题

### ISSUE THREAD

**Issue by vasth** [henson/ProxyPool#8]
咱们获取的这个代理地址是可以用的
117.143.109.143:80
但是我用http代理请求数据无法请求

**Comment by henson** [comment]
首先感谢你使用本程序，你提的问题涉及两个方面：

- 第一，免费的代理确实稳定性不是很好，时常一会能用一会不能用；

- 二，即便是有效的代理也有代理范围，不是所有区域都能使用，你例子中提供的代理IP就是国内IP，完全有可能不能访问国外网站数据，这是正常的。
