### ISSUE TITLE
程序运行久了，chan数量保持再100以上不变

### ISSUE THREAD

**Issue by alphayan** [henson/ProxyPool#9]
你好：
我将项目fork了一份，打包成docker跑在服务器上面，过几天查看日志，发现chan的数量保持在100以上，chan不消费了，程序不会自动爬取ip，需要重启：
![qq 20170918111101](https://user-images.githubusercontent.com/19967175/30528219-6f0cdcaa-9c63-11e7-855b-9f0924ae4d59.png)
请问这可能是什么情况导致的？

**Comment by henson** [comment]
IPChan里存的刚采集来的IP，排队待验证，不用管，经过验证处理，IPChan会自动降下来，降到100以下然后再启动采集进程。

**Comment by alphayan** [comment]
![qq 20170918145738](https://user-images.githubusercontent.com/19967175/30531568-cb8c53ac-9c81-11e7-91fc-483529780a00.png)
![qq 20170918145727](https://user-images.githubusercontent.com/19967175/30531563-c31c2878-9c81-11e7-8e51-c2dd7566e62a.png)
从16号一直等到18号，固定在127，这也是正常的吗？

**Comment by henson** [comment]
哦，那是卡死了，大概采集的那127个不是IP地址，无法去验证。可能又是那个代理站在搞鬼
